http://localhost:8080/terminal

--include
--silent 

Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRV

GET 

#GET /4

#POST 
#{
# "capacidad": 300,
# "piso": 100
#}

#PUT /5
#{
#  "capacidad": 300,
#  "piso": 100
#}

#DELETE /6
